// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mummybot;

namespace mummybot.Migrations
{
    [DbContext(typeof(mummybotDbContext))]
    [Migration("20200312143528_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("mummybot.Models.Blacklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("createdat")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Reason")
                        .HasColumnName("reason")
                        .HasColumnType("text");

                    b.Property<decimal>("UserId")
                        .HasColumnName("userid")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("blacklist");
                });

            modelBuilder.Entity("mummybot.Models.Guilds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("active")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("FilterInvites")
                        .HasColumnName("filterinvites")
                        .HasColumnType("boolean");

                    b.Property<string>("Goodbye")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("goodbye")
                        .HasColumnType("text")
                        .HasDefaultValue("**%user% has left**");

                    b.Property<decimal?>("GreetChl")
                        .HasColumnName("greetchl")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Greeting")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("greeting")
                        .HasColumnType("text")
                        .HasDefaultValue("**%user% has joined**");

                    b.Property<decimal>("GuildId")
                        .HasColumnName("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnName("guildname")
                        .HasColumnType("text");

                    b.Property<decimal>("OwnerId")
                        .HasColumnName("ownerid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Regex")
                        .HasColumnName("regex")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnName("region")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("guilds");
                });

            modelBuilder.Entity("mummybot.Models.Tags", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Author")
                        .HasColumnName("author")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("content")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnName("createdat")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Guild")
                        .HasColumnName("guild")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsCommand")
                        .HasColumnName("iscommand")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnName("lastused")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("LastUsedBy")
                        .HasColumnName("lastusedby")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(12)")
                        .HasMaxLength(12);

                    b.Property<int>("Uses")
                        .HasColumnName("uses")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("mummybot.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Avatar")
                        .HasColumnName("avatar")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnName("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("Joined")
                        .HasColumnName("joined")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nickname")
                        .HasColumnName("nickname")
                        .HasColumnType("text");

                    b.Property<bool>("TagBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tagbanned")
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("false");

                    b.Property<decimal>("UserId")
                        .HasColumnName("userid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasName("users_userid_key");

                    b.ToTable("users");
                });

            modelBuilder.Entity("mummybot.Models.UsersAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("ChangedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("changedon")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("GuildId")
                        .HasColumnName("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Nickname")
                        .HasColumnName("nickname")
                        .HasColumnType("text");

                    b.Property<decimal>("UserId")
                        .HasColumnName("userid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users_audit");
                });
#pragma warning restore 612, 618
        }
    }
}
